/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBottomBar: typeof import('./../components/app_bottom/AppBottomBar.vue')['default']
    AppDisplay: typeof import('./../components/app_top/AppDisplay.vue')['default']
    AppLeftBar: typeof import('./../components/AppLeftBar.vue')['default']
    AppTopBar: typeof import('./../components/app_top/AppTopBar.vue')['default']
    BilladmChart: typeof import('./../components/da_view/BilladmChart.vue')['default']
    BilladmChartDisplay: typeof import('./../components/da_view/BilladmChartDisplay.vue')['default']
    BilladmChartPanel: typeof import('./../components/da_view/BilladmChartPanel.vue')['default']
    BilladmFullScreen: typeof import('./../components/common/BilladmFullScreen.vue')['default']
    BilladmIcon: typeof import('./../components/BilladmIcon.vue')['default']
    BilladmIconButton: typeof import('./../components/BilladmIconButton.vue')['default']
    BilladmLabel: typeof import('./../components/text/BilladmLabel.vue')['default']
    BilladmModal: typeof import('./../components/BilladmModal.vue')['default']
    BilladmSelect: typeof import('./../components/BilladmSelect.vue')['default']
    BilladmTimeSelect: typeof import('./../components/BilladmTimeSelect.vue')['default']
    DataAnalysisView: typeof import('./../components/da_view/DataAnalysisView.vue')['default']
    DisplayIcon: typeof import('./../components/DisplayIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileDirSelect: typeof import('./../components/FileDirSelect.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LedgerSelect: typeof import('./../components/app_top/LedgerSelect.vue')['default']
    Pagination: typeof import('./../components/tr_view/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../components/settings_view/SettingsView.vue')['default']
    TransactionRecordOperation: typeof import('./../components/tr_view/TransactionRecordOperation.vue')['default']
    TransactionRecordTable: typeof import('./../components/tr_view/TransactionRecordTable.vue')['default']
    TransactionRecordView: typeof import('./../components/tr_view/TransactionRecordView.vue')['default']
    TrViewBottomStatistics: typeof import('./../components/app_bottom/TrViewBottomStatistics.vue')['default']
  }
}
